jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: false

      - name: Install Bundler 2.3 (works on ubuntu-20.04)
        run: gem install bundler -v "~> 2.3"

      - name: Install dependencies
        run: bundle install --path vendor/bundle

      - name: Build site
        run: bundle exec jekyll build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
